name: Build and Push to Artifact Registry

on: [push]

env:
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/test-gha-upload/test-img/

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/306223470399/locations/global/workloadIdentityPools/yongxuanzhang-gitlab-oidc/providers/yongxuan-gh-provider'

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --tag ${{ env.GAR_LOCATION }}
        working-directory: WORKING_DIRECTORY

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}
